// 株主優待データ構造と初期データ

export type Sector = 
  | '食品'
  | '小売'
  | '金融'
  | '不動産'
  | '電気・ガス'
  | '通信'
  | '運輸'
  | '観光・ホテル'
  | '医療・介護'
  | 'IT・情報通信'
  | '製造業'
  | 'その他';

export type BenefitType = 
  | '商品券'
  | '割引券'
  | 'サービス'
  | '株主優待品'
  | 'その他';

export type PriceRange = 
  | 'under_100k'
  | '100k_500k'
  | '500k_1m'
  | 'over_1m';

export interface StockBenefit {
  id: string;
  companyName: string;
  ticker: string;
  sector: Sector;
  exRightDate: string; // YYYY-MM-DD 権利確定日
  exDividendDate: string; // YYYY-MM-DD 権利落ち日
  minInvestment: number; // 最低投資額（円）
  benefitType: BenefitType;
  benefitDescription: string; // 優待内容の説明
  benefitDetails: string; // 詳細説明
  url?: string; // 企業ウェブサイト
}

export const priceRangeLabels: Record<PriceRange, string> = {
  'under_100k': '10万円以下',
  '100k_500k': '10～50万円',
  '500k_1m': '50～100万円',
  'over_1m': '100万円以上',
};

export function getPriceRange(amount: number): PriceRange {
  if (amount <= 100000) return 'under_100k';
  if (amount <= 500000) return '100k_500k';
  if (amount <= 1000000) return '500k_1m';
  return 'over_1m';
}

export const sampleData: StockBenefit[] = [
  {
    id: '1',
    companyName: 'オリックス',
    ticker: '8591',
    sector: '金融',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: '全国のオリックスレンタカー利用料金20%割引',
    benefitDetails: '年間を通じてオリックスレンタカーの利用料金が20%割引になります。',
    url: 'https://www.orix.co.jp',
  },
  {
    id: '2',
    companyName: 'マクドナルド',
    ticker: '2702',
    sector: '小売',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 300000,
    benefitType: '商品券',
    benefitDescription: 'マクドナルド優待券（年2回）',
    benefitDetails: '年2回、マクドナルドで使用できる優待券をお送りします。',
    url: 'https://www.mcdonalds.co.jp',
  },
  {
    id: '3',
    companyName: 'ヤマダ電機',
    ticker: '9831',
    sector: '小売',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: 'ヤマダ電機での買い物5%割引',
    benefitDetails: 'ヤマダ電機全店舗での買い物が5%割引になります。',
    url: 'https://www.yamada-denki.jp',
  },
  {
    id: '4',
    companyName: '日本航空',
    ticker: '9201',
    sector: '運輸',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 500000,
    benefitType: 'サービス',
    benefitDescription: 'JALマイルプレゼント',
    benefitDetails: '保有株数に応じてJALマイルをプレゼントします。',
    url: 'https://www.jal.co.jp',
  },
  {
    id: '5',
    companyName: 'すかいらーく',
    ticker: '3197',
    sector: '小売',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 150000,
    benefitType: '商品券',
    benefitDescription: 'すかいらーく優待食事券',
    benefitDetails: 'ガスト、バーミヤン、夢庵などで使用できる食事券。',
    url: 'https://www.skylark.co.jp',
  },
  {
    id: '6',
    companyName: 'ソフトバンクグループ',
    ticker: '9984',
    sector: '通信',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 200000,
    benefitType: 'その他',
    benefitDescription: 'ソフトバンク利用料金割引',
    benefitDetails: 'ソフトバンク携帯電話の利用料金が割引になります。',
    url: 'https://www.softbank.jp',
  },
  {
    id: '7',
    companyName: 'ファーストリテイリング',
    ticker: '9983',
    sector: '小売',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 1000000,
    benefitType: '割引券',
    benefitDescription: 'ユニクロ・GU店舗での割引',
    benefitDetails: 'ユニクロ・GU全店舗での買い物が10%割引になります。',
    url: 'https://www.fastretailing.com',
  },
  {
    id: '8',
    companyName: 'トヨタ自動車',
    ticker: '7203',
    sector: '製造業',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 2000000,
    benefitType: 'サービス',
    benefitDescription: 'トヨタ車の購入割引',
    benefitDetails: 'トヨタ車の新車購入時に割引が適用されます。',
    url: 'https://www.toyota.co.jp',
  },
  {
    id: '9',
    companyName: 'セブン＆アイ・ホールディングス',
    ticker: '3382',
    sector: '小売',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 100000,
    benefitType: '商品券',
    benefitDescription: 'セブンプレミアム商品引換券',
    benefitDetails: 'セブン-イレブン、イトーヨーカドーで使用できる商品引換券。',
    url: 'https://www.7andi.com',
  },
  {
    id: '10',
    companyName: 'NTTドコモ',
    ticker: '9437',
    sector: '通信',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 300000,
    benefitType: 'その他',
    benefitDescription: 'ドコモ利用料金割引',
    benefitDetails: 'ドコモ携帯電話の利用料金が割引になります。',
    url: 'https://www.nttdocomo.co.jp',
  },
  {
    id: '11',
    companyName: 'キャノン',
    ticker: '7751',
    sector: '製造業',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 500000,
    benefitType: '株主優待品',
    benefitDescription: 'キャノン製品詰め合わせ',
    benefitDetails: 'キャノンの製品やアクセサリーの詰め合わせをお送りします。',
    url: 'https://www.canon.co.jp',
  },
  {
    id: '12',
    companyName: '味の素',
    ticker: '2802',
    sector: '食品',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 200000,
    benefitType: '株主優待品',
    benefitDescription: '味の素製品詰め合わせ',
    benefitDetails: '味の素の各種製品をセットでお送りします。',
    url: 'https://www.ajinomoto.co.jp',
  },
  {
    id: '13',
    companyName: 'アサヒグループホールディングス',
    ticker: '2502',
    sector: '食品',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 300000,
    benefitType: '株主優待品',
    benefitDescription: 'アサヒ飲料詰め合わせ',
    benefitDetails: 'アサヒビール、飲料などの詰め合わせをお送りします。',
    url: 'https://www.asahigroup-holdings.com',
  },
  {
    id: '14',
    companyName: 'キリンホールディングス',
    ticker: '2555',
    sector: '食品',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 300000,
    benefitType: '株主優待品',
    benefitDescription: 'キリン飲料詰め合わせ',
    benefitDetails: 'キリンビール、飲料などの詰め合わせをお送りします。',
    url: 'https://www.kirin.co.jp',
  },
  {
    id: '15',
    companyName: 'サントリーホールディングス',
    ticker: '2587',
    sector: '食品',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 400000,
    benefitType: '株主優待品',
    benefitDescription: 'サントリー飲料詰め合わせ',
    benefitDetails: 'サントリーの各種飲料をセットでお送りします。',
    url: 'https://www.suntory.co.jp',
  },
  {
    id: '16',
    companyName: 'ソニーグループ',
    ticker: '6758',
    sector: 'IT・情報通信',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 800000,
    benefitType: '株主優待品',
    benefitDescription: 'ソニー製品詰め合わせ',
    benefitDetails: 'ソニーの各種製品やアクセサリーをお送りします。',
    url: 'https://www.sony.co.jp',
  },
  {
    id: '17',
    companyName: 'パナソニック',
    ticker: '6752',
    sector: '製造業',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 600000,
    benefitType: '株主優待品',
    benefitDescription: 'パナソニック製品詰め合わせ',
    benefitDetails: 'パナソニックの各種製品をお送りします。',
    url: 'https://www.panasonic.co.jp',
  },
  {
    id: '18',
    companyName: 'シャープ',
    ticker: '6753',
    sector: '製造業',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 500000,
    benefitType: '株主優待品',
    benefitDescription: 'シャープ製品詰め合わせ',
    benefitDetails: 'シャープの各種製品をお送りします。',
    url: 'https://www.sharp.co.jp',
  },
  {
    id: '19',
    companyName: '日本電信電話',
    ticker: '9432',
    sector: '通信',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 200000,
    benefitType: 'その他',
    benefitDescription: 'NTT利用料金割引',
    benefitDetails: 'NTT各種サービスの利用料金が割引になります。',
    url: 'https://www.ntt.co.jp',
  },
  {
    id: '20',
    companyName: 'KDDI',
    ticker: '9433',
    sector: '通信',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 250000,
    benefitType: 'その他',
    benefitDescription: 'au利用料金割引',
    benefitDetails: 'au携帯電話の利用料金が割引になります。',
    url: 'https://www.kddi.com',
  },
  {
    id: '21',
    companyName: '三菱UFJフィナンシャル・グループ',
    ticker: '8306',
    sector: '金融',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 300000,
    benefitType: 'その他',
    benefitDescription: '三菱UFJ銀行手数料割引',
    benefitDetails: '三菱UFJ銀行の各種手数料が割引になります。',
    url: 'https://www.mufg.jp',
  },
  {
    id: '22',
    companyName: '三井住友フィナンシャルグループ',
    ticker: '8316',
    sector: '金融',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 300000,
    benefitType: 'その他',
    benefitDescription: '三井住友銀行手数料割引',
    benefitDetails: '三井住友銀行の各種手数料が割引になります。',
    url: 'https://www.smbc.co.jp',
  },
  {
    id: '23',
    companyName: 'みずほフィナンシャルグループ',
    ticker: '8411',
    sector: '金融',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 300000,
    benefitType: 'その他',
    benefitDescription: 'みずほ銀行手数料割引',
    benefitDetails: 'みずほ銀行の各種手数料が割引になります。',
    url: 'https://www.mizuho-fg.co.jp',
  },
  {
    id: '24',
    companyName: 'ヤマト運輸',
    ticker: '9064',
    sector: '運輸',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: 'ヤマト運輸配送料金割引',
    benefitDetails: 'ヤマト運輸の配送料金が割引になります。',
    url: 'https://www.yamato-hd.co.jp',
  },
  {
    id: '25',
    companyName: '日本郵政',
    ticker: '6178',
    sector: '運輸',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 200000,
    benefitType: '割引券',
    benefitDescription: '郵便・配送サービス割引',
    benefitDetails: '日本郵便の各種サービスが割引になります。',
    url: 'https://www.japanpost.jp',
  },
  {
    id: '26',
    companyName: 'ANA',
    ticker: '9202',
    sector: '運輸',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 600000,
    benefitType: 'サービス',
    benefitDescription: 'ANAマイルプレゼント',
    benefitDetails: '保有株数に応じてANAマイルをプレゼントします。',
    url: 'https://www.ana.co.jp',
  },
  {
    id: '27',
    companyName: 'ホテルニューオータニ',
    ticker: '9706',
    sector: '観光・ホテル',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 500000,
    benefitType: 'サービス',
    benefitDescription: 'ホテルニューオータニ宿泊割引',
    benefitDetails: 'ホテルニューオータニグループの宿泊が割引になります。',
    url: 'https://www.newotani.co.jp',
  },
  {
    id: '28',
    companyName: 'プリンスホテル',
    ticker: '9708',
    sector: '観光・ホテル',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 400000,
    benefitType: 'サービス',
    benefitDescription: 'プリンスホテル宿泊割引',
    benefitDetails: 'プリンスホテルチェーンの宿泊が割引になります。',
    url: 'https://www.princehotels.com',
  },
  {
    id: '29',
    companyName: 'リーガロイヤルホテル',
    ticker: '9735',
    sector: '観光・ホテル',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 300000,
    benefitType: 'サービス',
    benefitDescription: 'リーガロイヤルホテル宿泊割引',
    benefitDetails: 'リーガロイヤルホテルの宿泊が割引になります。',
    url: 'https://www.rihga.co.jp',
  },
  {
    id: '30',
    companyName: 'JR東日本',
    ticker: '9020',
    sector: '運輸',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 600000,
    benefitType: '割引券',
    benefitDescription: 'JR東日本乗車券割引',
    benefitDetails: 'JR東日本の乗車券が割引になります。',
    url: 'https://www.jreast.co.jp',
  },
  {
    id: '31',
    companyName: '東京電力',
    ticker: '9501',
    sector: '電気・ガス',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 200000,
    benefitType: 'その他',
    benefitDescription: '電気料金割引',
    benefitDetails: '東京電力の電気料金が割引になります。',
    url: 'https://www.tepco.co.jp',
  },
  {
    id: '32',
    companyName: '関西電力',
    ticker: '9503',
    sector: '電気・ガス',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 200000,
    benefitType: 'その他',
    benefitDescription: '電気料金割引',
    benefitDetails: '関西電力の電気料金が割引になります。',
    url: 'https://www.kepco.co.jp',
  },
  {
    id: '33',
    companyName: '中部電力',
    ticker: '9502',
    sector: '電気・ガス',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 200000,
    benefitType: 'その他',
    benefitDescription: '電気料金割引',
    benefitDetails: '中部電力の電気料金が割引になります。',
    url: 'https://www.chuden.co.jp',
  },
  {
    id: '34',
    companyName: '東京ガス',
    ticker: '9531',
    sector: '電気・ガス',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 150000,
    benefitType: 'その他',
    benefitDescription: 'ガス料金割引',
    benefitDetails: '東京ガスのガス料金が割引になります。',
    url: 'https://www.tokyo-gas.co.jp',
  },
  {
    id: '35',
    companyName: '大阪ガス',
    ticker: '9532',
    sector: '電気・ガス',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 150000,
    benefitType: 'その他',
    benefitDescription: 'ガス料金割引',
    benefitDetails: '大阪ガスのガス料金が割引になります。',
    url: 'https://www.osakagas.co.jp',
  },
  {
    id: '36',
    companyName: 'ファーストフード・チェーン',
    ticker: '2798',
    sector: '小売',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 100000,
    benefitType: '商品券',
    benefitDescription: 'モスバーガー優待券',
    benefitDetails: 'モスバーガーで使用できる優待券をお送りします。',
    url: 'https://www.mos.co.jp',
  },
  {
    id: '37',
    companyName: 'ロイヤルホスト',
    ticker: '8200',
    sector: '小売',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 200000,
    benefitType: '商品券',
    benefitDescription: 'ロイヤルホスト優待食事券',
    benefitDetails: 'ロイヤルホストで使用できる食事券をお送りします。',
    url: 'https://www.royalhost.co.jp',
  },
  {
    id: '38',
    companyName: 'コロワイド',
    ticker: '7616',
    sector: '小売',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 100000,
    benefitType: '商品券',
    benefitDescription: '甘太郎・鳥番・海鮮居酒屋優待券',
    benefitDetails: '傘下の飲食店で使用できる優待券をお送りします。',
    url: 'https://www.colowide.co.jp',
  },
  {
    id: '39',
    companyName: 'ワタミ',
    ticker: '7522',
    sector: '小売',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 100000,
    benefitType: '商品券',
    benefitDescription: 'ワタミグループ優待食事券',
    benefitDetails: 'ワタミグループの飲食店で使用できる食事券。',
    url: 'https://www.watami.co.jp',
  },
  {
    id: '40',
    companyName: 'サイゼリヤ',
    ticker: '7581',
    sector: '小売',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 100000,
    benefitType: '商品券',
    benefitDescription: 'サイゼリヤ優待食事券',
    benefitDetails: 'サイゼリヤで使用できる食事券をお送りします。',
    url: 'https://www.saizeriya.co.jp',
  },
  {
    id: '41',
    companyName: 'ビックカメラ',
    ticker: '3048',
    sector: '小売',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: 'ビックカメラでの買い物割引',
    benefitDetails: 'ビックカメラ全店舗での買い物が割引になります。',
    url: 'https://www.biccamera.com',
  },
  {
    id: '42',
    companyName: 'コジマ',
    ticker: '7837',
    sector: '小売',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: 'コジマでの買い物割引',
    benefitDetails: 'コジマ全店舗での買い物が割引になります。',
    url: 'https://www.kojima.net',
  },
  {
    id: '43',
    companyName: 'ベスト電器',
    ticker: '8175',
    sector: '小売',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: 'ベスト電器での買い物割引',
    benefitDetails: 'ベスト電器全店舗での買い物が割引になります。',
    url: 'https://www.bestdenki.com',
  },
  {
    id: '44',
    companyName: '東急ストア',
    ticker: '3078',
    sector: '小売',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: '東急ストアでの買い物割引',
    benefitDetails: '東急ストア全店舗での買い物が割引になります。',
    url: 'https://www.tokyu-store.co.jp',
  },
  {
    id: '45',
    companyName: 'イオン',
    ticker: '8267',
    sector: '小売',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: 'イオンでの買い物割引',
    benefitDetails: 'イオン全店舗での買い物が割引になります。',
    url: 'https://www.aeon.co.jp',
  },
  {
    id: '46',
    companyName: 'ユニー・ファミリーマートホールディングス',
    ticker: '8028',
    sector: '小売',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: 'ファミリーマートでの買い物割引',
    benefitDetails: 'ファミリーマート全店舗での買い物が割引になります。',
    url: 'https://www.uny.co.jp',
  },
  {
    id: '47',
    companyName: 'ローソン',
    ticker: '2651',
    sector: '小売',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 100000,
    benefitType: '割引券',
    benefitDescription: 'ローソンでの買い物割引',
    benefitDetails: 'ローソン全店舗での買い物が割引になります。',
    url: 'https://www.lawson.co.jp',
  },
  {
    id: '48',
    companyName: 'セイコーグループ',
    ticker: '8050',
    sector: 'IT・情報通信',
    exRightDate: '2024-02-29',
    exDividendDate: '2024-03-01',
    minInvestment: 500000,
    benefitType: '株主優待品',
    benefitDescription: 'セイコー製品詰め合わせ',
    benefitDetails: 'セイコーの腕時計やアクセサリーをお送りします。',
    url: 'https://www.seiko.co.jp',
  },
  {
    id: '49',
    companyName: 'ミキモト',
    ticker: '7966',
    sector: '製造業',
    exRightDate: '2024-03-31',
    exDividendDate: '2024-04-01',
    minInvestment: 1500000,
    benefitType: '株主優待品',
    benefitDescription: 'ミキモト製品詰め合わせ',
    benefitDetails: 'ミキモトの真珠製品やアクセサリーをお送りします。',
    url: 'https://www.mikimoto.com',
  },
  {
    id: '50',
    companyName: 'テルモ',
    ticker: '4543',
    sector: '医療・介護',
    exRightDate: '2024-01-31',
    exDividendDate: '2024-02-01',
    minInvestment: 800000,
    benefitType: 'その他',
    benefitDescription: 'テルモ製品割引',
    benefitDetails: 'テルモの医療用品が割引で購入できます。',
    url: 'https://www.terumo.co.jp',
  },
];
